# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/student/Documents/jromeo/FinalProject/Waveform/Waveform/Waveform.srcs/sources_1/ip/myproject_0/myproject_0.xci
# IP: The module: 'myproject_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Documents/jromeo/FinalProject/Waveform/Waveform/Waveform.gen/sources_1/ip/myproject_0/constraints/myproject_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myproject_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/student/Documents/jromeo/FinalProject/Waveform/Waveform/Waveform.srcs/sources_1/ip/myproject_0/myproject_0.xci
# IP: The module: 'myproject_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Documents/jromeo/FinalProject/Waveform/Waveform/Waveform.gen/sources_1/ip/myproject_0/constraints/myproject_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myproject_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
