Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    dense:
      Precision:
        accum: auto
        bias: ap_fixed<16,6>
        result: auto
        weight: ap_fixed<16,4>
      ReuseFactor: 256
      Trace: true
    dense_1:
      Precision:
        accum: auto
        bias: ap_fixed<14,8>
        result: auto
        weight: ap_fixed<18,6>
      ReuseFactor: 256
      Trace: true
    dense_1_relu:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 256
      TableSize: 1024
      Trace: true
    dense_2:
      Precision:
        accum: auto
        bias: ap_fixed<10,8>
        result: auto
        weight: ap_fixed<20,6>
      ReuseFactor: 256
      Trace: true
    dense_2_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 256
      TableSize: 1024
      Trace: true
    dense_relu:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 256
      TableSize: 1024
      Trace: true
    input_1:
      Precision:
        result: auto
      Trace: true
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<20,14>
    ReuseFactor: 256
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: Input.dat
InputShapes:
  input_1:
  - 100
KerasModel: !keras_model 'hls4ml_prj/keras_model.keras'
OutputDir: hls4ml_prj
OutputPredictions: Output.dat
OutputShapes:
  layer6_out:
  - 4
Part: xc7a200tsbg484-1
ProjectName: myproject
Stamp: f1548f67
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteTar: false
  WriteWeightsTxt: true
